### ISSUE TITLE
 Does not work behind reverse proxy

### ISSUE THREAD

**Issue by travisspencer** [curityio/authenticator-maven-archetype#6]
The [LinkedIn authenticator plug-in](https://github.com/curityio/linkedin-authenticator/pull/5/files#diff-b2e81af73ac52041cc25fd8be2416365R152) did not work when used behind a reverse proxy. This is the case because this archetype included code that used the [callback URL of the request](https://github.com/curityio/authenticator-maven-archetype/blob/master/oauth-authenticator-archetype/src/main/resources/archetype-resources/src/main/java/authentication/CallbackRequestHandler.java#L100).

**Comment by mtrojanowski** [comment]
This has been fixed in version 2.5.0
